// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/AlecSmith96/fourth-floor-exercise/adapters"
	"github.com/AlecSmith96/fourth-floor-exercise/rest"
)

// Injectors from service.go:

// InitialiseService creates a new Service instance with server and logger
func InitialiseService() (Service, error) {
	config, err := adapters.NewConfig()
	if err != nil {
		return Service{}, err
	}
	configRest := config.Rest
	configLogging := config.Logging
	logger, err := adapters.NewLogger(configLogging)
	if err != nil {
		return Service{}, err
	}
	configAuth := config.Auth
	twitchRequests := adapters.NewTwitchAdapter(logger, configAuth)
	analyticsAdapter := adapters.NewAnalyticsAdapter(logger)
	engine := rest.NewRouter(logger, twitchRequests, analyticsAdapter)
	server := rest.NewHTTPServer(configRest, engine)
	service := Service{
		Server: server,
		Logger: logger,
	}
	return service, nil
}
